[project]
name = "1001-tracklists-api"
version = "0.0.1"
description = "An unofficial API to create Python objects with data from 1001tracklists.com."
authors = [{ name = "Martin Tracey", email = "matracey@outlook.ie" }]
requires-python = ">=3.12"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = ["parsel>=1.9.1", "requests~=2.32.3", "pydantic~=2.9.2"]


[project.optional-dependencies]
dev = [
    "black~=24.10.0",
    "flake8~=7.1.1",
    "isort~=5.13.2",
    "pylance~=0.20.0",
    "pylint~=3.3.2",
    "flake8-pyproject~=1.2.3",
    "pdm-bump~=0.9.9.post1",
]


[project.scripts]
1001tl = "tracklists_cli.cli:main"


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true


[tool.flake8]
# B = bugbear
# E = pycodestyle errors
# F = flake8 pyflakes
# W = pycodestyle warnings
# B9 = bugbear opinions
# ISC = implicit-str-concat
select = ["B", "E", "F", "W"]
ignore = [
  # slice notation whitespace, invalid
  "E203",
  # line length, handled by bugbear B950
  "E501",
  # bin op line break, invalid
  "W503",
]
# up to 88 allowed by bugbear B950
max-line-length = 88
per-file-ignores = [
  # __init__ modules export names
  "**/__init__.py: F401, F403",
]


[tool.isort]
profile = "black"
line_length = 88


[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311", "py312"]
